name: Frontend CI/CD

on:
  push:
    branches:
      - main   # faqat main branchga push bo'lganda ishga tushadi

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: server connaction
      uses: appleboy/ssh-action@master 
      with:
        host: ${{ secrets.SERVER_HOST }} 
        username: ${{ secrets.SERVER_USERNAME }} 
        password: ${{ secrets.SERVER_PASSWORD }}
        script: | 
          curl -fsSL https://deb.nodesource.com/setup_22.x | sudo -E bash -
          sudo apt install -y nodejs
          
          cd /home/fintechadmin/platform/frontend-test
          git stash
          git pull origin main
          # npm install
          npm run build
          pm2 restart all
          echo "âœ… Deployment tugadi!"